openapi: '3.0.0'
info:
  version: 1.0.0
  title: Planaday API
  license:
    name: MIT
servers:
  - url: https://api.planaday.com/v1
paths:
  /courses:
    get:
      summary: List all courses
      operationId: listCourses
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An paged array of courses
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Courses'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a course
      operationId: createCourses
      responses:
        201:
          description: Course created successfully
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /courses/{courseId}:
    get:
      summary: Info for a specific course
      operationId: showCourseById
      parameters:
        - name: courseId
          in: path
          required: true
          description: The id of the course to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Courses'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /students:
    get:
      summary: List all students
      operationId: listStudents
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An paged array of students
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Students'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a student
      operationId: createStudents
      responses:
        201:
          description: Student created successfully
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /students/{studentId}:
    get:
      summary: Info for a specific student
      operationId: showStudentById
      parameters:
        - name: studentId
          in: path
          required: true
          description: The id of the student to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Students'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Course:
      required:
        - id
        - title
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        instructor_id:
          type: string
    Courses:
      type: array
      items:
        $ref: '#/components/schemas/Course'
    Student:
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        course_id:
          type: string
    Students:
      type: array
      items:
        $ref: '#/components/schemas/Student'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string